# Generated by Django 2.2.3 on 2019-10-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blood_sugar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
