# Generated by Django 2.2.3 on 2019-10-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191023_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.IntegerField(verbose_name='Blood sugar'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.IntegerField(verbose_name='Measurement number'),
        ),
    ]
