# Generated by Django 2.2.3 on 2019-10-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191023_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='info',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
